/**
 * feedback — ONE call per product event; the module fans out to the matching
 * haptic (expo-haptics, in every build) and sound (expo-audio, present only in
 * native builds made after 2026-07-17).
 *
 * Duolingo-discipline: exactly four events, palette generated by
 * scripts/make-sounds.mjs. Frequency scales inversely with reward weight —
 * tick is nearly silent, success is the fanfare. Add a fifth only with a
 * design-level reason.
 *
 * OTA safety: expo-audio is REQUIRED LAZILY inside try/catch. On installed
 * builds whose native side predates it, the require (or its native call)
 * throws once, we mark audio 'unavailable', and every call degrades to
 * haptics-only. Feedback must never crash cooking.
 *
 * Audio session: ambient + mix-with-others — people cook to podcasts; we never
 * duck or interrupt them, and we respect the silent switch.
 */
/* eslint-disable @typescript-eslint/no-require-imports -- Metro resolves static
   assets via require(), and expo-audio must be required lazily (OTA safety). */
import * as Haptics from 'expo-haptics';

import { getFeedbackPrefs } from './feedbackPrefs';

type SoundName = 'tick' | 'pop' | 'timerDone' | 'success';

// Static requires so Metro bundles the assets; tiny (all four < 100 KB total).
const SOUND_SOURCES: Record<SoundName, number> = {
  tick: require('../../assets/sounds/tick.wav'),
  pop: require('../../assets/sounds/pop.wav'),
  timerDone: require('../../assets/sounds/timer-done.wav'),
  success: require('../../assets/sounds/success.wav'),
};

type AudioPlayerLike = { seekTo(sec: number): void; play(): void };
let players: Partial<Record<SoundName, AudioPlayerLike>> | 'unavailable' | null = null;

function ensureAudio(): Partial<Record<SoundName, AudioPlayerLike>> | null {
  if (players === 'unavailable') return null;
  if (players) return players;
  try {
    const audio = require('expo-audio') as typeof import('expo-audio');
    void audio.setAudioModeAsync({
      playsInSilentMode: false,
      interruptionMode: 'mixWithOthers',
      shouldPlayInBackground: false,
    });
    players = {
      tick: audio.createAudioPlayer(SOUND_SOURCES.tick),
      pop: audio.createAudioPlayer(SOUND_SOURCES.pop),
      timerDone: audio.createAudioPlayer(SOUND_SOURCES.timerDone),
      success: audio.createAudioPlayer(SOUND_SOURCES.success),
    };
    return players;
  } catch {
    players = 'unavailable'; // Old native build — haptics-only from here on.
    return null;
  }
}

function play(name: SoundName): void {
  if (!getFeedbackPrefs().sounds) return;
  try {
    const p = ensureAudio()?.[name];
    if (!p) return;
    p.seekTo(0);
    p.play();
  } catch {
    // Never let a sound break an interaction.
  }
}

function haptic(fire: () => Promise<void>): void {
  if (!getFeedbackPrefs().haptics) return;
  fire().catch(() => {});
}

export const feedback = {
  /** Small confirmations heard many times: check-offs, toggles, selections. */
  tick(): void {
    haptic(() => Haptics.selectionAsync());
    play('tick');
  },
  /** Something entered the world: pantry item added, timer started. */
  pop(): void {
    haptic(() => Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light));
    play('pop');
  },
  /** A foreground timer reached zero. */
  timerDone(): void {
    haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success));
    play('timerDone');
  },
  /** The big one — finishing a cook ("I made this!"). */
  success(): void {
    haptic(() => Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success));
    play('success');
  },
};
